version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wallet_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: wallet_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: wallet_rabbitmq
    restart: always
    ports:
      - '5672:5672'    
      - '15672:15672'   
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata:
  redisdata:
